[tool.poetry]
name = "rollbot"
version = "1.0.0"
description = "Rollbot is a Discord bot for rolling dice."
authors = ["Thijs Miedema <mail@tmiedema.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10.6"
py-cord = {extras = ["speed"], version="^2.4.1"}
numpy = "^1.22.1"
matplotlib = "^3.5.1"
lark-parser = "^0.12.0"
redis = "^4.5.4"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
